### PR TITLE
Adding some info icons and links

### PR DESCRIPTION
**Pull request by matzew**

### CODE REVIEW

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:

* The code changes conform to the contributing & code style guides for this component (if they exist)
* A component owner should review your change (we've tagged these above)
* Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
* If updating server component this PR should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
* Ensure JIRA is up to date before & after merge (e.g. deployment notes, tester notes, release notes, fix version)
* Any SonarQube issues should be addressed where applicable (use your own judgement)

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.
Fhcap PR will be generated automatically.
To deploy your changes to a cluster place comment in this PR with pattern [x][y] where x=deploy and y=clustername you wish to deploy. 
You can also deploy your change manually using fhcap-cli

**Comment by matzew** [comment]
@odra can you review ?

**Comment by odra** [comment]
LGTM - but since the shrinkwrap file was changed we need a version bump for it as well

**Comment by matzew** [comment]
shouldn't version just bumped on releases? not on any PR ?

**Comment by odra** [comment]
I think if we change the dependencies and/or shrinkwrap files we just need to bump the patch version.

**Comment by matzew** [comment]
once we do a release, they need to be update anyways, right ? 

I see no value in bumping them on every (dependency) change, to be honest

**Comment by matzew** [comment]
added those version updates, for now :)

**Pull request merged**
