### PR TITLE
fix(dep) : Unable to add the version 0.7.4 of the lib fh-amqp-js in another projects and updated deps

### PR DESCRIPTION
**Pull request by camilamacedo86**
# Jira:
https://issues.jboss.org/browse/RHMAP-20872

# What:
- Upgrade dependencies without break changes which impact this project
- Fix npm shrinkwrap in order to allow this lib be used as a dep in other projects.

# Why:

The npm-shrinkwrap is broken which cause issues when trying to add this project as dep in other's libs/projects as the following example. Similar issues occur when we try to install new versions of deps here in this project as well. 

Run `npm install --save --save-exact fh-amqp-js@0.7.4`

```
npm WARN saveError extraneous: to-iso-string@0.0.2 /Users/cmacedo/work/fh-mbaas/node_modules/fh-amqp-js/node_modules/mocha/node_modules/to-iso-string
npm WARN saveError extraneous: proxyquire@0.4.0 /Users/cmacedo/work/fh-mbaas/node_modules/fh-amqp-js/node_modules/proxyquire
npm WARN saveError extraneous: xunit-file@0.0.9 /Users/cmacedo/work/fh-mbaas/node_modules/fh-amqp-js/node_modules/xunit-file
npm WARN saveError extraneous: mkdirp@0.5.1 /Users/cmacedo/work/fh-mbaas/node_modules/fh-amqp-js/node_modules/xunit-file/node_modules/mkdirp
npm WARN saveError extraneous: minimist@0.0.8 /Users/cmacedo/work/fh-mbaas/node_modules/fh-amqp-js/node_modules/xunit-file/node_modules/mkdirp/node_modules/minimist

``` 

# How
- Run `rm -rf node_modules/ && rm -rf npm-shrinkwrap`
- Run `npm install && npm shrinkwrap`
- Upgrade deps via the npm manager `npm install --save --save-exact  async@1.5.2`  

# Steps to verify:

Check if the CI finish with success

### CODE REVIEW

**Review by davidffrench — APPROVED** [review]
LGTM

**Comment by damienomurchu** [comment]
Re: using 0.7.4 as a dependency in other projects, I wonder if this is an npm version issue, as you can see from the PR [here]https://github.com/feedhenry/fh-cachekey-client/pull/5) that using 0.7.4 in fh-amqp-js was not an issue.

**Review by damienomurchu — APPROVED** [review]
Dependency bumps look good to me :+1:

**Review by austincunningham — APPROVED** [review]
Changes look good, couple of major version bumps but only in the devDependencies, If the build passes you should be good to merge

**Pull request merged**
